repeat events after updating them
apostrophecms/apostrophe-events pull request #51
Opened 2022-08-24 12:46 UTC by ETLaurent

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-08-25 17:09 UTC, boutell requested changes
What happens if the event was repeated properly the first time? If that inserted 5 events the first time, does saving it again insert 5 more or do the relevant fields get cleared after each repeat to prevent that in some way? I don't see any indication of that.

2022-08-26 09:42 UTC, ETLaurent commented
> What happens if the event was repeated properly the first time? If that inserted 5 events the first time, does saving it again insert 5 more or do the relevant fields get cleared after each repeat to prevent that in some way? I don't see any indication of that.

@boutell  Indeed it will insert 5 more events.
Thing is when we edit a single day event to change it to recursive, it won't create the expected events if we use afterInsert (which seems to be problematic). 
We could avoid creating new replicated events when children events exist (using parentId field), and we could also update the "children" events with the new values of the parent one. 
Wdyt?

2022-08-29 13:48 UTC, boutell requested changes
This is a reasonable incremental improvement, but note you need to handle err in all cases.

2022-08-29 13:48 UTC, boutell commented on index.js
> +        .toArray(function(err, docs) {
Handle `err`

2022-08-29 17:57 UTC, boutell approved these changes

2022-08-30 10:16 UTC, merged